--- 
- name: Create databases
  hosts: 192.168.1.101
  tasks:
  - name: Create a new database with name 'bobdata'
    mysql_db:
      name: customers
      state: present
  - name: Copy database dump file to remote host and restore it to database 'my_db'
    win_copy:
      src: 'C:\Users\Dell\Desktop\AWS\mysql\all_files.sql'
      dest: /root/
      remote_src: yes      
  - name: Dump all databases to hostname.sql
    mysql_db:
      state: dump
      name: all
      target: /root/all_files.sql
      remote_src: yes
      



