---
- name: Install Mysql on Ubuntu
  hosts: 192.168.1.110
  tasks:
  - name: Download sources
    get_url:
      url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
      dest: /root/mysql
      command: rpm -ivh mysql-community-release-el7-5.noarch.rpm
  - name: Install package
    apt:
      name: /root/mysql/mysql-community-release-el7-5.noarch.rpm
      state: present
  - name: Install MySQL
    apt: 
      name=mysql-server
      state=installed
  - name: Add mysql-user
    mysql_user:
      name=mysql_service
      password=12345
      priv=*.*:ALL
      state=present
  handlers:
  - name: start mysql
    service: name=mysql
             enabled=yes
             state=started
  - name: restart mysql
    service: 
      name=mysql
      enabled=yes
      state=restarted
