---
- name: Install Mysql on Ubuntu
  hosts: 192.168.1.110
  tasks:
  - name: install SQL
    apt: 
      name=mysql-server
      state=installed
  - name: Add mysql-user
    mysql_user:
      name=mysql_service
      password=12345
      priv=*.*:ALL
      state=present
  handlers:
  - name: start mysql
    service: name=mysql
             enabled=yes
             state=started
  - name: restart mysql
    service: 
      name=mysql
      enabled=yes
      state=restarted
