---
- name: Install Mysql on Ubuntu
  hosts: 192.168.30.93
  tasks:
  - name: install SQL
    apt: 
      name=mysql-server
      name=python-mysqldb
      state=installed
- name: Add mysql-user
  hosts: 192.168.30.93
  tasks:    
  - name: Add mysql-user
    mysql_user:
      name=pramod
      password=12345
      priv=*.*:ALL
      state=present
  handlers:
  - name: start mysql
    service: 
      name=mysql
      enabled=yes
      state=started
  - name: restart mysql
    service: 
      name=mysql
      enabled=yes
      state=restarted
- name:Database Automation
  hosts:192.168.30.93
  tasks:  
  - name: Create a new database with name 'bobdata'
    mysql_db:
      name: customers
      state: present
  - name: Copy database dump file to remote host and restore it to database 'my_db'
    copy:
      src: C:\Users\Dell\Desktop\AWS\mysql\all_files.sql
      dest: /root/
  - name: Dump all databases to hostname.sql
    mysql_db:
      state: dump
      name: all
      target: /root/all_files.sql    
